// <auto-generated />
using HTEC.ChampionsLeague.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HTEC.ChampionsLeague.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HTEC.task.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwayTeam");

                    b.Property<string>("Group");

                    b.Property<string>("HomeTeam");

                    b.Property<DateTime>("KickoffAt");

                    b.Property<string>("LeagueTitle");

                    b.Property<int>("Matchday");

                    b.Property<string>("Score");

                    b.HasKey("Id");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("HTEC.task.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Draw");

                    b.Property<int>("GoalDifference");

                    b.Property<int>("Goals");

                    b.Property<int>("GoalsAgainst");

                    b.Property<int>("Lose");

                    b.Property<int>("PlayedGames");

                    b.Property<int>("Points");

                    b.Property<int>("TableId");

                    b.Property<string>("Team");

                    b.Property<int>("Win");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Standing");
                });

            modelBuilder.Entity("HTEC.task.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Group");

                    b.Property<string>("LeagueTitle");

                    b.Property<int>("Matchday");

                    b.HasKey("Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("HTEC.task.Standing", b =>
                {
                    b.HasOne("HTEC.task.Table", "Table")
                        .WithMany("Standing")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
